/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.openbravo.pos.inventory;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.customers.DataLogicCustomers;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.GridLayout;
import java.awt.Window;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFrame;

/**
 *
 * @author sysfore17
 */
public class JFrameRoles extends javax.swing.JFrame {
 int x = 530;
    int y = 270;
    int width = 320;
    int height = 50;
    private java.util.List<BeanInfo> rolesList;
    private java.util.List<String> selectedList;
    JCheckBox[] checkBoxList=null;
    public static boolean isclose=false;
    
    /**
     * Creates new form JFrameRoles
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jPanelRole = new javax.swing.JPanel();
        jPanelButtons = new javax.swing.JPanel();
        Okay = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                WindowClosingActionPerformed(evt);
            }
        });

        jPanelRole.setAutoscrolls(true);
        jPanelRole.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane.setViewportView(jPanelRole);

        getContentPane().add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanelButtons.setPreferredSize(new java.awt.Dimension(100, 40));

        Okay.setText("Ok");
        Okay.setPreferredSize(new java.awt.Dimension(60, 30));
        Okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkayActionPerformed(evt);
            }
        });
        jPanelButtons.add(Okay);

        jButtonCancel.setText("Cancel");
        jButtonCancel.setAlignmentX(2.0F);
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonCancel);

        getContentPane().add(jPanelButtons, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
      isclose=true;
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void OkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkayActionPerformed
        isclose=false;
       for(Component component : jPanelRole.getComponents()) {
        if(component instanceof JCheckBox){
          if(((JCheckBox)component).isSelected()){
            javax.swing.JCheckBox  m_jChkRoleName= (JCheckBox)component; 
          selectedList.add(m_jChkRoleName.getActionCommand());
        }
        }
    }
        System.out.println("after saying okay"+selectedList.size());
    dispose();
    }//GEN-LAST:event_OkayActionPerformed

    private void WindowClosingActionPerformed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_WindowClosingActionPerformed
        isclose=true;
    }//GEN-LAST:event_WindowClosingActionPerformed

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Okay;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelRole;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables

public static java.util.List<String> showMessage(Component parent, DataLogicCustomers dlSales,AppView app) {
        Window window = getWindow(parent);
        JFrameRoles myMsg;
        if (window instanceof Frame) {
            myMsg = new JFrameRoles((Frame) window, true);
        } else {
            myMsg = new JFrameRoles((Dialog) window, true);
        }
         
       return myMsg.init(dlSales, app);

    }
public JFrameRoles(Frame frame, boolean b) {
        
        setBounds(x, y, width, height);
    }

 private JFrameRoles(Dialog dialog, boolean b) {
       
        setBounds(x, y, width, height);
        //To change body of generated methods, choose Tools | Templates.
    }
        private static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }
        
  private java.util.List<String>  init(DataLogicCustomers dlcustomers, AppView app) {
        try {
            initComponents();
            this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
             selectedList=new ArrayList();
            jPanelRole.setLayout(new GridLayout(0, 2, 3, 0));
            this.setSize(300, 200);
            this.setResizable(false);
            rolesList = dlcustomers.getRolesList();
            int numberCheckBox = rolesList.size();
            checkBoxList = new JCheckBox[numberCheckBox];
            int dimension=40;

           for (int i = 0; i < numberCheckBox; i++) {
            javax.swing.JCheckBox  m_jChkRoleName= new javax.swing.JCheckBox();    
            m_jChkRoleName.setLabel(rolesList.get(i).getName());
            m_jChkRoleName.setActionCommand(rolesList.get(i).getId());
            jPanelRole.add(m_jChkRoleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, dimension, -1, -1));
            dimension=dimension+40;  
           } 
          } catch (BasicException ex) {
            Logger.getLogger(JDialogRoles.class.getName()).log(Level.SEVERE, null, ex);
        }
        setTitle("Roles");
        setVisible(true);
        System.out.println("in init method"+selectedList.size());
        return selectedList;
    }
  
  



}
